### ISSUE TITLE
Phaser 3!!!

### ISSUE THREAD

**Issue by Thundros** [jjppof/goldensun_html5#1]
Hello @jjppof ! I absolutely LOVE this! PLEASE keep up the GREAT work! <3

Second, PLEASE make it Phaser 3!

**Comment by Thundros** [comment]
@jjppof Hello?

**Comment by jjppof** [comment]
I'll give it a try latter. For now, I updated to 2.15.0.

**Comment by Thundros** [comment]
@jjppof : How long?

**Comment by jjppof** [comment]
Not soon. I'll make the game things first, then I can think about it. Changing to Phaser 3 is not essential.
