### ISSUE TITLE
Abilities can have a "max quantity", right now there is only "quantity"

### ISSUE THREAD

**Issue by immortaleeb** [jjppof/goldensun_html5#164]
Example: The sword card ability reduces an enemies attack between 25% and 50% [1].

I don't see way to specify the 50% (max quantity) in the database file.

[1] https://goldensun.fandom.com/wiki/Card_Psynergy_set

**Comment by jjppof** [comment]
solved on edc5bd922fbffe294ea96acd5358eabded4d2281.
Now the `"quantity"` property of an effect also supports an array of two elements. If this array is given, a value between the first and second values will be randomly chosen.
