### ISSUE TITLE
Create game event for BGM and SFX

### ISSUE THREAD

**Issue by jjppof** [jjppof/goldensun_html5#228]
For [GameEvent](https://github.com/jjppof/goldensun_html5/blob/master/base/game_events/GameEvent.ts) reference, please check the [docs](https://gshtml5.org/docs/classes/game_events_gameevent.gameevent.html).

Create a game event that manipulates the sounds of the game. It should play, pause and stop SFX or BGM audios. Please see [Audio](https://github.com/jjppof/goldensun_html5/blob/master/base/Audio.ts) class.

**Comment by slucase** [comment]
Doing
