### ISSUE TITLE
Hi, jippof, please take a look 

### ISSUE THREAD

**Issue by SteveLiGt** [jjppof/goldensun_html5#23]
hi, **jjppof, ( I do not know if you can see this message, if you could, please reply to me when you have a chance)**

first, I would like to appreciate people like you to make this GS engine, although based on our Demo, there still plenty that we could do. A bit about me, I was one of the fan of our GS, and after played the GS Generation 3, I felt the story leftover so much to tell us. And personally, I enjoyed play gen 1st and 2nd much more then gen 3nd. 
For me, the most fancinating part of GS is the mechanism of PSYCHIC AND DINJIN, I was always look for if there is a game like it, but so far, no luck. So I started to wondering if it is possible that we could do something to rebuild even partially of the GS ( **Again, thanks for making the GS engine, it is amazing.)** 
**_I was currently working on Computer science degree on a 4-year school ( I did have some prior programming experience for c and c++, but very little for HTML5 and JavaScript)_**

so I download the HTML5 ( again, not so familiar with it), so I ran it, it gave a web address, when I loaded it in my Chrome, it gave me exactly same web page like the Demo. 
**With all my respect, Is that all we have currently? ( I know you are not going to make the animation or map, but is it possible for people who interested at this to make it by ourselves by making use of what you provided here? If so, where should we get started? Do we need to have some JavaScript in order to do it?  // if so, let me know, I could self-taught some JavaScript during my leisure time.**

**Comment by jjppof** [comment]
Hello Steve! Glad you liked it!
First, as you said, this repository has just enough resources to show its functionalities. But, on your computer or in a fork of this repo, you can do whatever you want. Feel free!

But as you can see, there are a lot of mechanics to be developed and I need help. If you want to do so, I think that would be good if we have a little chat about it then I can explain everything that I'm planning. Call me on discord (jjppof#5856) or skype (jjppof) if you want to do so.

For general talk about this project, please join [GSHC discord](https://discord.gg/pVgZUa) at #programming channel.

Thanks!

**Comment by SteveLiGt** [comment]
steve_li#0958
my discord name, I sent you a friend request.
( Please accept it, also, I was already join the GSHC server.)
