### ISSUE TITLE
Create psynergy stone game event

### ISSUE THREAD

**Issue by jjppof** [jjppof/goldensun_html5#268]

**Comment by sdtv9507** [comment]
I may work on this. I'll make sure i have all the assets for this

**Comment by jjppof** [comment]
> I may work on this. I'll make sure i have all the assets for this

Nice! You may want to get some references from ChestEvent.ts.

**Comment by sdtv9507** [comment]
Did the psynergy Stone healed all pp or a fixed amount set depending on the event?

**Comment by jjppof** [comment]
> Did the psynergy Stone healed all pp or a fixed amount set depending on the event?

All PP.

**Comment by sdtv9507** [comment]
I have everything mostly done, but the event (an NPC event), wont animate while on the field, i have to trigger It so that It starts the animation

**Comment by sdtv9507** [comment]
Ok, i fixed it
