### ISSUE TITLE
remove kill_all_sprites in utils.ts

### ISSUE THREAD

**Issue by jjppof** [jjppof/goldensun_html5#278]

**Comment by MrBushidoBrownn** [comment]
I commented out the function. I believe this is what you are asking.

**Comment by jjppof** [comment]
> I commented out the function. I believe this is what you are asking.

I need it to be removed and all references to it should be replaced by a similar functionality. If you're using vscode, please highlight the function name and press ALT + SHIFT + F12 to find all references.

**Comment by jjppof** [comment]
b46bd339b422e426eff471d0500aacd7eb808fbd
