### ISSUE TITLE
Game freezes when switching to any other app/window and then returning to the game

### ISSUE THREAD

**Issue by abhishek7997** [jjppof/goldensun_html5#331]
Replication:

- run the game.
- open any other app/window (such as discord) for some time (few minutes should be ok).
- Go back to the game window.
- Unable to use arrow keys to move character, the river animation stops.
- When using D to check collision box, the collision box appears to be irregular.

![image](https://user-images.githubusercontent.com/68701271/136437655-0edb5659-14fc-4b7f-8401-49a927c22345.png)

![image](https://user-images.githubusercontent.com/68701271/136437626-02337705-8c39-4ae8-b409-5e25c5dfb127.png)

https://user-images.githubusercontent.com/68701271/136437673-b619a2df-7b0a-413d-a13b-c0b1137d4e1f.mp4

(Please ignore the blinking cursor (caret), its there because I have turned on caret browsing in chrome)

**Comment by jjppof** [comment]
It seems that it's happening due to monitors with higher frequency than 60 fps...

**Comment by jjppof** [comment]
Changing to Phaser 2.19 fixed the bug.
