### ISSUE TITLE
Crash related to tightrope created with lash

### ISSUE THREAD

**Issue by ImaginaryUse201** [jjppof/goldensun_html5#362]
![goldensuncrash](https://user-images.githubusercontent.com/98982931/152420644-55ad3f2a-260c-4810-9483-7ea7bc0488ea.gif)
I've just realized my cursor is in the gif, hope you don't mind.

**Comment by jjppof** [comment]
> I've just realized my cursor is in the gif
Not a problem 🙂
Thanks for uploading it!

Hmm... what's the FPS you're running it? Press F then you will be able to see it.

**Comment by ImaginaryUse201** [comment]
Ok, I found what causes it (I think). It's a combination of holding right to walk the tightrope, and then at the end of the tightrope holding up to get off while also holding right. I don't know why this freezes the game, but it consistently does with those inputs.

**Comment by jjppof** [comment]
I was able to reproduce now, many thanks! Now I need to solve it 😁
