### ISSUE TITLE
Reveal before tightrope reveals whole screen

### ISSUE THREAD

**Issue by MilesBHuff** [jjppof/goldensun_html5#378]
![image](https://user-images.githubusercontent.com/6566982/161081729-194078a5-4e80-4242-b4bf-a21d342cb1a3.png)
Casting 'Reveal' and then jumping onto a tightrope results in the entire screen being revealed;  although the effect still ends at its original boundary.

**Comment by jjppof** [comment]
Good catch!

**Comment by MilesBHuff** [comment]
I actually think there were bugs like this in the original game, but maybe I'm remembering wrong.

**Comment by jjppof** [comment]
At least making the same mistakes 😂😅

**Comment by jjppof** [comment]
Fixed with 76e5317a68846d98307b1caa16499765a78d296e
