### ISSUE TITLE
Game soft-locks when buying Antidote from rare items shop

### ISSUE THREAD

**Issue by MilesBHuff** [jjppof/goldensun_html5#382]
![image](https://user-images.githubusercontent.com/6566982/161097234-7dc343e9-b16b-43e6-b301-688ab79ba1e2.png)
This happened after I sold Piers's antidotes.
It says there are none in stock -- I'm guessing maybe selling those antidotes did not increase the number of copies available in the rare items shop, even though it got it listed?

**Comment by MilesBHuff** [comment]
btw, if you know how to get out of this one, lmk -- I'd like to do a battle now that I've got everyone all kitted-out.  :)

**Comment by jjppof** [comment]
Will check, but this one seems to be an error in items_db. Antidote is marked there as `rare_item`, which is not true.

**Comment by jjppof** [comment]
> btw, if you know how to get out of this one (potentially with the "sliders" feature), lmk -- I'd like to do a battle now that I've got everyone all kitted-out. :) I also want to try Lift. I'll leave the tab open.

No way to get out of this one. I checked here and in this situation, the game crashed internally.

**Comment by MilesBHuff** [comment]
> Antidote is marked there as `rare_item`, which is not true.

There are others with that same designation, like Elixir.

**Comment by jjppof** [comment]
Fixed!
