### ISSUE TITLE
Adept classes are not reflected in battle

### ISSUE THREAD

**Issue by MilesBHuff** [jjppof/goldensun_html5#383]
I swapped Isaac and Garret's djinni, but both had only their default class's psynergy in battle.

**Comment by jjppof** [comment]
Hmm, this one seems to be working here:
![image](https://user-images.githubusercontent.com/7890647/161100778-3bb7ca30-322a-40c7-b592-10182fd374e3.png)

![image](https://user-images.githubusercontent.com/7890647/161100820-9ccf2ee8-67a0-4f9c-9e9e-1d61fd024be4.png)

**Comment by MilesBHuff** [comment]
I can't repro.  Maybe I made a mistake and didn't switch them beforehand like I thought I did?  Humm.
