### ISSUE TITLE
Lift Gem doesn't show as equipped

### ISSUE THREAD

**Issue by MilesBHuff** [jjppof/goldensun_html5#386]
The Lift Gem doesn't show as equipped unless you equip it to someone else in the party;  in which case, it will show as equipped until you close and reopen the menu, at which time it will, once again, appear to be unequipped.  This is more than cosmetic:  it even gives you an option to equip it;  but doing this doesn't actually do anything.

In any case, the gem's psynergy shows up in the menu, so this bug doesn't seem to have any impact on gameplay.

**Comment by jjppof** [comment]
Could not reproduce this one. Do you have a detailed step-by-step for it?

**Comment by MilesBHuff** [comment]
Ah, I'll need to get this running locally for that.  It's probably inevitable that I'll end-up contributing at some point (as I am a full-time web-developer and *love* the Golden Sun series), but I can't do that at this exact moment.

**Comment by jjppof** [comment]
No problem, take your time!
Finding bugs is already veeery helpful!
And looking forward to receiving contributions ☺

**Comment by jjppof** [comment]
![cheat](https://user-images.githubusercontent.com/7890647/161105871-15287ae5-9ba0-4a0e-b775-98a40b270d76.gif)
Maybe this can help you get there faster.

**Comment by MilesBHuff** [comment]
Lol I just got through doing it manually :D
I was unable to reproduce, so I'm closing.
