### ISSUE TITLE
Game crashed on selling hat

### ISSUE THREAD

**Issue by MilesBHuff** [jjppof/goldensun_html5#392]
This happened after I sold a Leather Cap.  I've been unable to reproduce the issue, but I wanted to report it in case you knew what was going on.
![image](https://user-images.githubusercontent.com/6566982/162824819-5122e361-08f6-4326-bede-3d11ebe559d0.png)

**Comment by MilesBHuff** [comment]
Happened again when buying a Festival Coat to replace Sheba's Adepts Clothes:  
![image](https://user-images.githubusercontent.com/6566982/162825313-03b6a8e9-de17-4a8c-8e75-50812245c9df.png)

**Comment by jjppof** [comment]
Ok to close this one?

**Comment by MilesBHuff** [comment]
This one is different from #393 (it references completely different files), but we can close it if you want.  I've yet to reproduce it.

**Comment by jjppof** [comment]
Ok, will keep open, not sure whether it's the same thing. Need to check.

**Comment by MilesBHuff** [comment]
#392 references `SellRepairMenu.ts` and `ShopMenu.ts`;  while #393 references `InventoryWindow.ts`.
As well:  #392 happened on selling items, while #393 happened on buying items.

**Comment by MilesBHuff** [comment]
Fixed on my local, in f6008238971910a6b4602d9fe6129a09a77c8f17.
