### ISSUE TITLE
Possible to "fly" around in obstacle course

### ISSUE THREAD

**Issue by MilesBHuff** [jjppof/goldensun_html5#396]
Freeze the pillars, and then get to here:
![image](https://user-images.githubusercontent.com/6566982/162834735-a81d7d29-edbb-4d1b-8f12-a2ee9da88996.png)
Then walk to the right, and enjoy:
![image](https://user-images.githubusercontent.com/6566982/162834791-dfeee214-da04-49f0-b0d7-0255030b0096.png)
![image](https://user-images.githubusercontent.com/6566982/162834848-5dcab2e4-3296-474f-bd68-5a5bedb35be5.png)
![image](https://user-images.githubusercontent.com/6566982/162834922-69dfc2e9-c7bf-4c1d-8594-2972b59b69de.png)
![image](https://user-images.githubusercontent.com/6566982/162835021-831a0d5e-a877-4ae6-96fa-f772f0e5ca9f.png)

**Comment by jjppof** [comment]
Hmm, this was a bug in the map construction. Fixed at bf179f1f74025f59c88eb8ecfde53529d55d1611
