### ISSUE TITLE
Can't jump from viney pillar to wall

### ISSUE THREAD

**Issue by MilesBHuff** [jjppof/goldensun_html5#397]
It will let me jump from the wall to this pillar, but not from this pillar to the wall:
![image](https://user-images.githubusercontent.com/6566982/162835182-a02d393f-5219-41f2-a8cf-71a6e532e758.png)

**Comment by jjppof** [comment]
Hmm, not being able to reproduce this one...
![bug3](https://user-images.githubusercontent.com/7890647/162838100-58c0c863-af4a-425c-b48c-de23238f28c0.gif)

**Comment by MilesBHuff** [comment]
Huh.  It's definitely still happening for me.
I need to learn how to make .gif screenshots.
![image](https://user-images.githubusercontent.com/6566982/162843145-cca64663-1ea5-42d5-a7b8-e310a39a4d75.png)

**Comment by MilesBHuff** [comment]
I just opened the game in a new tab, and it's working now.  I guess you must have fixed it?  Or it was bugged in my other tab, even though I'd entered and left the area many times?

**Comment by jjppof** [comment]
Making gifs will help a lot. I use [screentogif](https://www.screentogif.com/). If possible, also record showing the keys you're using (press K).

**Comment by jjppof** [comment]
> I guess you must have fixed it?

I did nothing

> Or it was bugged in my other tab

Probably this.

**Comment by MilesBHuff** [comment]
I'll close this... for now.  I'll reopen if I can reproduce on a new tab.
