### ISSUE TITLE
Jumping down from viney pillar randomly picks between climbing and jumping

### ISSUE THREAD

**Issue by MilesBHuff** [jjppof/goldensun_html5#398]
![image](https://user-images.githubusercontent.com/6566982/162835326-a4068ca9-499e-42f8-8c81-551ab08b25d6.png)

**Comment by jjppof** [comment]
This happens when jumping from ice pillar and then quickly returning back to it. Even though the event queue gives preference to climb events, something is making only jump events go to the queue for a short period of time.

**Comment by MilesBHuff** [comment]
It would be kind of neat if we could choose -- maybe jumping when sprinting, and climbing otherwise?  But that would probably confuse players.
I guess the status quo is confusing, too.  Idk.

**Comment by jjppof** [comment]
At least for now I'll keep it simple (preferences hard-coded). I strongly believe that problems like this one will appear in the future when people start to build maps. If I see that it happens with frequency, I'll create something to let users decide based on tile position and layer height.
