### ISSUE TITLE
A couple of my savefiles are *huge*

### ISSUE THREAD

**Issue by MilesBHuff** [jjppof/goldensun_html5#399]
[save (8).zip](https://github.com/jjppof/goldensun_html5/files/8467901/save.8.zip)
![image](https://user-images.githubusercontent.com/6566982/162836197-e3eb8a0c-ab62-44b8-b087-f71ce3295e8f.png)

**Comment by jjppof** [comment]
That's indeed huge. Can you upload it somehow?

**Comment by MilesBHuff** [comment]
I did upload it -- check my OP carefully;  just above the image is a file download link:  "save (8).zip".

**Comment by jjppof** [comment]
Indeed. Just noticed! Many thanks!

**Comment by jjppof** [comment]
All the info there is indeed important. Will find a way to compress (maybe just uglify will be enough...).

**Comment by MilesBHuff** [comment]
Are you sure?  It seems like almost the entire file is just endless `false`s:
![image](https://user-images.githubusercontent.com/6566982/162844137-109105bd-a2b0-4288-8a41-c0f5779d2e2d.png)

**Comment by MilesBHuff** [comment]
If those `false`s are necessary, maybe you could replace them with a bitmask?  It'd store way easier, and use much less memory -- 1/8 as much, in fact.

**Comment by MilesBHuff** [comment]
Regarding uglify:  I'd rather you didn't, since having a hand-editable savefile is very handy.  Zipping it up is a better idea, and would have better gains anyway.

**Comment by jjppof** [comment]
> maybe you could replace them with bitmasks?

That's a good alternative. Initially, I wanted to keep it as a json file so users could edit it easily, mainly the ones that aren't developers. But If I see there's no way, I can start doing stuff like this.

> Zipping it up is a better idea, and would have better gains anyway.

Agreed.

**Comment by jjppof** [comment]
To be honest, I've been wanting to refactor TileEvent data structures for a long time... the way how it's organized is far from being intelligent. When I first built it, I had no idea of what I was doing...
Those `false`s are necessary, but they could not be...

**Comment by MilesBHuff** [comment]
Bitmasks are honestly more user-friendly than an array of `false`s -- the huge `false` arrays take up too much of the visual field and are hard to grok, imho;  and the equivalence of `true`:`1`::`false`:`0` is pretty universal, and easily taught if not known.

Ah, refactoring to where none of this is even necessary is also a promising idea!

**Comment by jjppof** [comment]
> Ah, refactoring to where none of this is even necessary is also a promising idea!

Will think about it in a near future.

Will test the bitmask first to see whether only this would be enough to reduce most of the data.

**Comment by jjppof** [comment]
Probably fixed with 92fbf96723a7a196e3ce039c6ce9f4ff394c9673
