### ISSUE TITLE
Implement Kolima Forest's opening effects

### ISSUE THREAD

**Issue by MilesBHuff** [jjppof/goldensun_html5#411]
Just creating an issue to track this, since I didn't see any others.
While difficult to implement;  once finished, it would be pretty easy to add to the demo world's forest instance.
![image](https://user-images.githubusercontent.com/6566982/163309554-400b3093-53f7-438c-93b0-bc4130996631.png)

**Comment by jjppof** [comment]
Which effect exactly? The bubbles?

**Comment by MilesBHuff** [comment]
I guess there are 4 separate effects here:

1. Adepts lying down
2. Purpling of the screen
3. Sparkles falling from the sky
4. Blue bubbles
5. Blue bubbles reacting to sparkles falling from the sky

I could see users wanting to use these effects in custom maps;  and as they are in GS1, they have to get implemented at some point.

**Comment by jjppof** [comment]
1, 2, 4 and 5 are Game Events.
3 could also be a Game Event to control Particles System, if you want, you can open an issue for it.
