### ISSUE TITLE
Implement desert mechanics

### ISSUE THREAD

**Issue by MilesBHuff** [jjppof/goldensun_html5#412]
The following mechanics need to be implemented for deserts to work properly:

1. Rivers of sand (and waterfalls thereof)
2. Sandstorm particles
3. Temperature gauge, adept reactions to the temperature, and damage from getting too hot
4. Sand creatures that appear on Reveal
5. The Sand Psynergy (TLA)
6. Tornadoes (both small and large;  and an option to make large tornadoes teleport people somewhere else)
7. The Douse Psynergy (TBS;  needed for tornadoes)

**Comment by jjppof** [comment]
We could open separate issues for the topics.

1. Not for first release.
2. Not for first release.
3. I think that's too specific... if it's me who's going to do it, it would be veeery low priority.
4. Can be done with Game Events.
5. Not for first release.
6. Can be done with Game Events.
7. Already done. Can be achieved with Douse + Game Events.

**Comment by MilesBHuff** [comment]
Yeah, that's probably best.  This is a lot for just one issue.  Maybe there should be a Desert Milestone in GitHub, and then we just put all these issues under it.

**Comment by jjppof** [comment]
Created #415 #416 #417
