### ISSUE TITLE
Fix Char status menu in Djinn menu

### ISSUE THREAD

**Issue by SamuelPhang** [jjppof/goldensun_html5#464]
Char status menu from pressing L in the Djinn list window

![char_status_djinn_menu_bug](https://user-images.githubusercontent.com/40727683/210285395-aadf11fa-18ab-4912-a4bd-f0c2566a4561.gif)

**Comment by jjppof** [comment]
What's the sequence of commands to reproduce this? I could not understand.
Thanks!

**Comment by SamuelPhang** [comment]
Press L in the Djinn menu to get to the chat status window. Then the cursor will act like it's still in the Djinn menu (when pressing arrow keys) and the other buttons won't work. When trying to exit this window, control will be passed back to the character sprite but the window will not disappear

**Comment by jjppof** [comment]
Are you able to reproduce this in the online version? By pressing arrow keys within the menu opened by L is doing nothing than the expected behavior.

**Comment by SamuelPhang** [comment]
Ah, this was caused by one of my local changes. (I forgot I was still on my own branch). Will close this issue

**Comment by jjppof** [comment]
Got it. Thanks!
