### ISSUE TITLE
Game freezes when repeatedly buying and equipping same item from shop

### ISSUE THREAD

**Issue by SamuelPhang** [jjppof/goldensun_html5#476]
![broken_shop](https://user-images.githubusercontent.com/40727683/212809028-25f30ceb-2382-41db-be68-4e618dd6a705.gif)

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'equipped')
    at g.unequip_item (MainChar.ts:462:24)
    at g.equip_item (MainChar.ts:429:18)
    at e.BuyArtifactsMenu.equip_new_item (BuyArtifactsMenu.ts:203:41)
```

**Comment by SamuelPhang** [comment]
@jjppof can you explain what was causing the game to freeze? Just curious

**Comment by jjppof** [comment]
The implementer of the shop wasn't using the MainChar API to add and remove items, this was causing some issues with the `index` property of the `ItemSlot`s.
These issues, in this example, were leading to a crash when you received a game ticket.
