### ISSUE TITLE
Healer doesn't recognize venom as poison

### ISSUE THREAD

**Issue by SamuelPhang** [jjppof/goldensun_html5#479]
![broken_cure_poison](https://user-images.githubusercontent.com/40727683/213386568-cc3655f6-3c56-494a-9702-5fc58936dbd5.gif)

**Comment by jjppof** [comment]
Nice catch!

**Comment by SamuelPhang** [comment]
@jjppof I think the commit above is missing the edge case when one party member has poison and one has venom. In this case the healer will still not recognized the venom'ed character as being poisoned.

**Comment by jjppof** [comment]
Got you mean, you're right. Reopening.

**Comment by jjppof** [comment]
I hope it's fixed now.
