### ISSUE TITLE
The engine looks poorly scaled with DPI 125%

### ISSUE THREAD

**Issue by RafaelTrepaUnCarballo** [jjppof/goldensun_html5#498]
Windows automatically enables dpi scaling in screens relatively smalls like my 15" laptop. The UI looks uncomfortably small without it.

Most games and emulators skip the scaling, protecting the graphics from windows' fractionary scaling. If it's possible, the same should be implemented for the Golden Sun engine.

Engine at 100% dpi vs Engine at 125%
![imagen](https://user-images.githubusercontent.com/16591467/221306605-bd97b767-466b-465b-8f47-523d48407672.png)

Engine vs mGBA on DPI 125%
![imagen](https://user-images.githubusercontent.com/16591467/221305299-82506f5d-d8dd-44a0-a9a9-1974d749957b.png)

**Comment by jjppof** [comment]
Possibly solved at 8dffe0bd0cda406014f7202c96841e56fcc29e41

**Comment by jjppof** [comment]
Use [`ignore_system_scaling`](https://github.com/jjppof/goldensun_html5/wiki/Game-initialization-settings) to control it.
