### ISSUE TITLE
[Windows] Increasing the window size in the Title Screen and then loading a save file rescales the graphics to x1

### ISSUE THREAD

**Issue by RafaelTrepaUnCarballo** [jjppof/goldensun_html5#500]
Basically, the window remains magnified, but the window content only fills a fraction of it.

![imagen](https://user-images.githubusercontent.com/16591467/222401723-212dea62-d43b-4911-b27e-f05b8dc99c1e.png)

It's a small situational bug that can easily fixed by resizing the screen again.
HTML version kinda suffer the same bug, although it's less important since it doesn't create black space.

**Comment by jjppof** [comment]
Is good to point out that the save file holds the scaling factor that was being used on save. So when restoring it, it will change the canvas size.
