### ISSUE TITLE
Using Douse will sliding on ice turns off collision and can lead to passing through objects

### ISSUE THREAD

**Issue by syntheticdinosaur** [jjppof/goldensun_html5#503]
Doing the snowland ice skate puzzle, using douse field psynergy while sliding and 1 or 2 tiles away from a rock leads to the character passing through the rock without collision. I have tested this repeatedly. If helpful, I can record it, too.

Thanks for doing this project, btw :)

**Comment by jjppof** [comment]
Hello! Many thanks for finding this bug. I'll try to reproduce it on my side, but if you're able to record it, it would be very helpful. Consider using [screentogif](https://www.screentogif.com/) to record this issue.

Thanks!

**Comment by jjppof** [comment]
nvm, I was able to reproduce it.

![douse_issue](https://user-images.githubusercontent.com/7890647/229106368-0ba3e5d6-4821-48af-86cb-1d3696cfe9f7.gif)
