### ISSUE TITLE
Combat freeze when attacking a dead enemy with a Djinn

### ISSUE THREAD

**Issue by JCalHij** [jjppof/goldensun_html5#547]
Reproducible.

- Launch the demo
- Go directly to Briggs
- Isaac -> Flint -> Left enemy
- Garet -> Scorch -> Left enemy
- Sheba -> Gust -> Left enemy

Sheba and Isaac defeat the enemy, then Garet tries to use Scorch, but the game is frozen:

```
Battle.ts:1270 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'set_status')
    at N.manage_djinn_or_summon_ability (Battle.ts:1270:61)
    at N.battle_phase_combat (Battle.ts:791:24)
```

Issue does not appear when Garet selects another enemy. Perhaps Garet is not switching targets?

I tried checking other behaviors, such as:

- Isaac -> Flint -> Left enemy
- Garet -> Normal attack-> Left enemy
- Sheba -> Gust -> Left enemy

And Garet attacks nothing, but the game is not freezing. This supports the theory of not switching targets.

**Comment by jjppof** [comment]
I was able to reproduce this one.

Many thanks!
