### ISSUE TITLE
Screenshots in the README?

### ISSUE THREAD

**Issue by neuromancer** [jjppof/goldensun_html5#64]
I think people will be more interested in testing this neat re-implementation and maybe collaborate with some code if you show the current state of this reimplementation in the README.

**Comment by jjppof** [comment]
Oh, that's a nice suggestion. Will do it, thanks!

**Comment by jjppof** [comment]
We'll add something in the README, but you can always check the [projects](https://github.com/jjppof/goldensun_html5/projects). They're always updated.
