### ISSUE TITLE
HP and PP recovery on battle.

### ISSUE THREAD

**Issue by jjppof** [jjppof/goldensun_html5#79]
Add HP and PP recovery system on the battle system.

**Comment by sdtv9507** [comment]
Ok, I would like to do this. Just to be sure, it's only HP and PP recovery, not status effects; and both Items and Psynergy should be able to do the recovery

**Comment by jjppof** [comment]
> only HP and PP recovery

Yes. Only HP and PP.  A Player (MainChar and Enemy) has the `hp_recovery` and `pp_recovery` properties that should be used for this purpose.

> Items and Psynergy should be able to do the recovery

Even though the answer to this question is Yes, the mechanism should be independent of Items, Abilities, or whatever.

The only thing you need to do here in order to solve this issue is recover HP/PP using `hp_recovery`/`pp_recovery` properties at the end of the battle round (and show a log in the case this recovering is different of zero. Also consider negative recovering).

**Comment by sdtv9507** [comment]
Wait, so this is like a regen effect where you recover at the end if the turn as long as these properties aren't 0. And if they are less than 0, its like a poison effect??

**Comment by jjppof** [comment]
Yes, the difference is that it's not a status and it can be positive (in original game, always positive).

**Comment by sdtv9507** [comment]
Ok, I'll get to work on this.
