### ISSUE TITLE
Build Enemy AI in battle.

### ISSUE THREAD

**Issue by jjppof** [jjppof/goldensun_html5#84]

**Comment by MilesBHuff** [comment]
Some monsters have their own AIs;  how are users of the GSHTML5 engine to create custom AIs without coding?  And how is the engine to incorporate their scripts?

**Comment by jjppof** [comment]
There's no spec for this. Everything needs to be thought.
And yeah, I reeeeally want to avoid users writing code, need to think of a system that allows having different behavior for enemies without coding.

**Comment by MilesBHuff** [comment]
Maybe pretend it's Pokémon?  Allow users to select 4 moves for each monster.  In the code, each move can be classified into damage vs status vs healing.  The AI can cleverly attempt to use moves that are strong against an enemy's resistances ("type", in Pokémon terms), and AI will prioritize using status effect moves when no enemy has that move's status.  Whenever an AI's party member is at or below 1/3 health, they will prioritize healing that party member with their best-available heal.  Enemies with 1/4 or less PP will stop using damaging Psynergy if they have a healing Psynergy.

**Comment by jjppof** [comment]
Yeah, those are all valid points. Whenever someone starts doing this, we can precisely define what we want initially based on your comment.
